-- LPM 0.1.0. Generated by tools/build.py.
local loaders, loaded = {}, {}
local hostRequire = require
local function require(n)
 if loaded[n] ~= nil then return loaded[n] end
 if not loaders[n] then return hostRequire(n) end
 local v=loaders[n](); if v==nil then v=true end; loaded[n]=v; return v
end
loaders['data'] = function()
-- Non-executing parser for: return { literal table }.
local M = {}
function M.parse(s)
    assert(type(s) == "string" and #s <= 262144, "Manifest exceeds 256 KiB")
    local p, nodes = 1, 0
    local function fail(msg) error("Data syntax at byte " .. p .. ": " .. msg, 0) end
    local function skip()
        while true do
            local _, e = s:find("^%s+", p)
            if e then p = e + 1 end
            if s:sub(p, p + 1) ~= "--" then return end
            if s:sub(p + 2, p + 3) == "[[" then
                local stop = s:find("]]", p + 4, true)
                if not stop then fail("Unclosed comment") end
                p = stop + 2
            else
                p = (s:find("\n", p + 2, true) or #s) + 1
            end
        end
    end
    local function take(c) skip(); if s:sub(p, p) ~= c then fail("Expected " .. c) end; p = p + 1 end
    local function ident()
        skip(); local v = s:match("^[_%a][_%w]*", p)
        if v then p = p + #v end
        return v
    end
    local function quoted()
        local q = s:sub(p,p); p=p+1; local out={}
        local esc={n="\n",r="\r",t="\t",a="\a",b="\b",f="\f",v="\v",["\\"]="\\",['"']='"',["'"]="'"}
        while p <= #s do
            local c=s:sub(p,p); p=p+1
            if c==q then return table.concat(out) end
            if c=="\n" or c=="\r" then fail("Newline in string") end
            if c=="\\" then
                c=s:sub(p,p); p=p+1
                if esc[c] then out[#out+1]=esc[c]
                elseif c:match("%d") then
                    local digits=c
                    for _=1,2 do local d=s:sub(p,p); if not d:match("%d") then break end; digits=digits..d; p=p+1 end
                    local n=tonumber(digits); if n>255 then fail("Escape out of range") end
                    out[#out+1]=string.char(n)
                else fail("Unsupported escape") end
            else out[#out+1]=c end
        end
        fail("Unclosed string")
    end
    local value
    value=function(depth)
        skip(); nodes=nodes+1
        if depth>24 or nodes>20000 then fail("Data too complex") end
        local c=s:sub(p,p)
        if c=='"' or c=="'" then return quoted() end
        if c=="{" then
            p=p+1; local out,seen,nextIndex={}, {},1
            skip()
            while s:sub(p,p)~="}" do
                local k,v
                if s:sub(p,p)=="[" then
                    p=p+1; k=value(depth+1); take("]"); take("="); v=value(depth+1)
                else
                    local old=p; local id=ident(); skip()
                    if id and s:sub(p,p)=="=" then p=p+1; k=id; v=value(depth+1)
                    else p=old; k=nextIndex; nextIndex=nextIndex+1; v=value(depth+1) end
                end
                if type(k)~="string" and type(k)~="number" then fail("Invalid key") end
                if seen[k] then fail("Duplicate key") end
                seen[k]=true; out[k]=v; skip()
                c=s:sub(p,p)
                if c=="," or c==";" then p=p+1; skip()
                elseif c~="}" then fail("Expected comma or closing brace") end
            end
            p=p+1; return out
        end
        local number=s:match("^-?%d+%.?%d*",p)
        if number then p=p+#number; return tonumber(number) end
        local id=ident()
        if id=="true" then return true elseif id=="false" then return false end
        fail("Expected literal, found " .. tostring(id or c))
    end
    if ident()~="return" then fail("Expected return") end
    local result=value(0); skip()
    if s:sub(p,p)==";" then p=p+1; skip() end
    if p<=#s then fail("Trailing executable content") end
    assert(type(result)=="table", "Expected returned table")
    return result
end
function M.serialize(v)
    local function emit(x,depth)
        assert(depth<=24, "Data too deep")
        if type(x)=="string" then return string.format("%q",x):gsub("\\\n","\\n") end
        if type(x)=="number" or type(x)=="boolean" then return tostring(x) end
        assert(type(x)=="table", "Unsupported data")
        local keys={}; for k in pairs(x) do keys[#keys+1]=k end
        table.sort(keys,function(a,b) if type(a)~=type(b) then return type(a)<type(b) end; return a<b end)
        local out={"{"}
        for _,k in ipairs(keys) do out[#out+1]="["..emit(k,depth+1).."]="..emit(x[k],depth+1).."," end
        out[#out+1]="}"; return table.concat(out)
    end
    return "return "..emit(v,0).."\n"
end
return M

end
loaders['semver'] = function()
local M={}
function M.parse(v)
    assert(type(v)=="string", "Version must be a string")
    local a,b,c=v:match("^(%d+)%.(%d+)%.(%d+)$")
    assert(a, "Expected stable major.minor.patch: "..v)
    for _,n in ipairs({a,b,c}) do assert(n=="0" or n:sub(1,1)~="0", "Leading zero in version"); assert(#n<=6,"Version component too large") end
    return {tonumber(a),tonumber(b),tonumber(c)}
end
function M.compare(a,b)
    a=M.parse(a); b=M.parse(b)
    for i=1,3 do if a[i]~=b[i] then return a[i]<b[i] and -1 or 1 end end
    return 0
end
function M.satisfies(v,r)
    assert(type(r)=="string", "Constraint must be a string")
    if r=="*" then M.parse(v); return true end
    local op,base=r:match("^([%^~])(.+)$")
    if not op then return M.compare(v,r)==0 end
    local x=M.parse(base); local upper
    if op=="~" then upper={x[1],x[2]+1,0}
    elseif x[1]>0 then upper={x[1]+1,0,0}
    elseif x[2]>0 then upper={0,x[2]+1,0}
    else upper={0,0,x[3]+1} end
    return M.compare(v,base)>=0 and M.compare(v,table.concat(upper,"."))<0
end
return M

end
loaders['sha256'] = function()
local I = {}
local bit = assert(bit32, "bit32 required")
local band, bxor, bnot, rshift, rrotate = bit.band, bit.bxor, bit.bnot, bit.rshift, bit.rrotate
local MOD = 4294967296
local function u32(n)
    return string.char(
        math.floor(n / 16777216) % 256,
        math.floor(n / 65536) % 256,
        math.floor(n / 256) % 256,
        n % 256
    )
end
local function read32(s, p)
    local a, b, c, d = s:byte(p, p + 3)
    assert(d, "Truncated integer")
    return ((a * 256 + b) * 256 + c) * 256 + d
end
local K = {
    0x428a2f98,
    0x71374491,
    0xb5c0fbcf,
    0xe9b5dba5,
    0x3956c25b,
    0x59f111f1,
    0x923f82a4,
    0xab1c5ed5,
    0xd807aa98,
    0x12835b01,
    0x243185be,
    0x550c7dc3,
    0x72be5d74,
    0x80deb1fe,
    0x9bdc06a7,
    0xc19bf174,
    0xe49b69c1,
    0xefbe4786,
    0x0fc19dc6,
    0x240ca1cc,
    0x2de92c6f,
    0x4a7484aa,
    0x5cb0a9dc,
    0x76f988da,
    0x983e5152,
    0xa831c66d,
    0xb00327c8,
    0xbf597fc7,
    0xc6e00bf3,
    0xd5a79147,
    0x06ca6351,
    0x14292967,
    0x27b70a85,
    0x2e1b2138,
    0x4d2c6dfc,
    0x53380d13,
    0x650a7354,
    0x766a0abb,
    0x81c2c92e,
    0x92722c85,
    0xa2bfe8a1,
    0xa81a664b,
    0xc24b8b70,
    0xc76c51a3,
    0xd192e819,
    0xd6990624,
    0xf40e3585,
    0x106aa070,
    0x19a4c116,
    0x1e376c08,
    0x2748774c,
    0x34b0bcb5,
    0x391c0cb3,
    0x4ed8aa4a,
    0x5b9cca4f,
    0x682e6ff3,
    0x748f82ee,
    0x78a5636f,
    0x84c87814,
    0x8cc70208,
    0x90befffa,
    0xa4506ceb,
    0xbef9a3f7,
    0xc67178f2,
}
function I.sha256(s)
    local len = #s
    s = s
        .. "\128"
        .. string.rep("\0", (55 - len) % 64)
        .. u32(math.floor(len / 536870912))
        .. u32((len * 8) % MOD)
    local h = {
        0x6a09e667,
        0xbb67ae85,
        0x3c6ef372,
        0xa54ff53a,
        0x510e527f,
        0x9b05688c,
        0x1f83d9ab,
        0x5be0cd19,
    }
    for start = 1, #s, 64 do
        if start > 1 and (start - 1) % 16384 == 0 and sleep then
            sleep(0)
        end
        local w = {}
        for j = 1, 16 do
            w[j] = read32(s, start + (j - 1) * 4)
        end
        for j = 17, 64 do
            local x, y = w[j - 15], w[j - 2]
            w[j] = (
                w[j - 16]
                + bxor(rrotate(x, 7), rrotate(x, 18), rshift(x, 3))
                + w[j - 7]
                + bxor(rrotate(y, 17), rrotate(y, 19), rshift(y, 10))
            ) % MOD
        end
        local a, b, c, d, e, f, g, hh = table.unpack(h)
        for j = 1, 64 do
            local t1 = (
                hh
                + bxor(rrotate(e, 6), rrotate(e, 11), rrotate(e, 25))
                + bxor(band(e, f), band(bnot(e), g))
                + K[j]
                + w[j]
            ) % MOD
            local t2 = (
                bxor(rrotate(a, 2), rrotate(a, 13), rrotate(a, 22))
                + bxor(band(a, b), band(a, c), band(b, c))
            ) % MOD
            hh, g, f, e, d, c, b, a = g, f, e, (d + t1) % MOD, c, b, a, (t1 + t2) % MOD
        end
        local v = { a, b, c, d, e, f, g, hh }
        for j = 1, 8 do
            h[j] = (h[j] + v[j]) % MOD
        end
    end
    local out = {}
    for j = 1, 8 do
        out[j] = u32(h[j])
    end
    return table.concat(out)
end

return function(s)
 return (I.sha256(s):gsub(".", function(c) return string.format("%02x", c:byte()) end))
end


end
loaders['core'] = function()
local data, semver, sha256 = require("data"), require("semver"), require("sha256")
local M={version="0.1.0"}
local MAX_FILE, MAX_TOTAL = 1048576, 8388608
local function sorted(t) local a={}; for k in pairs(t) do a[#a+1]=k end; table.sort(a); return a end
local function name(n)
    assert(type(n)=="string" and #n<=64 and n:match("^[a-z][a-z0-9_-]*$"), "Invalid package name: "..tostring(n)); return n
end
local function path(p)
    assert(type(p)=="string" and #p>0 and #p<=240 and not p:find("[^%w_./%-]"), "Invalid package path")
    assert(p:sub(1,1)~="/" and p:sub(-1)~="/" and not p:find("//",1,true),"Path must be relative")
    for part in p:gmatch("[^/]+") do assert(part~="." and part~="..", "Path traversal rejected") end
    return p
end
local function deps(d)
    assert(type(d)=="table", "dependencies must be a table")
    for n,r in pairs(d) do name(n); semver.satisfies("0.0.0",r) end
    return d
end
local function repo(r)
    assert(type(r)=="table" and type(r.github)=="string", "Expected GitHub repository")
    assert(r.github:match("^[%w_.-]+/[%w_.-]+$"), "Invalid owner/repo")
    assert(type(r.ref or "main")=="string" and # (r.ref or "main")<=160, "Invalid repository ref")
    if r.path and r.path~="" then path(r.path) end
    return r
end
local function manifest(m,n)
    assert(m.manifestVersion==1 and m.name==n,"Manifest name or schema mismatch")
    semver.parse(m.version)
    assert(m.type=="library" or m.type=="application", "Unknown package type")
    deps(m.dependencies or {})
    assert(type(m.files)=="table" and next(m.files), "Manifest must list files")
    local targets={}; local count=0
    for src,dst in pairs(m.files) do
        path(src); path(dst); count=count+1; assert(count<=256,"Too many files")
        assert(not targets[dst],"Duplicate install target"); targets[dst]=true
    end
    for a in pairs(targets) do for b in pairs(targets) do assert(a==b or b:sub(1,#a+1)~=a.."/","File/directory target collision") end end
    if m.entry then path(m.entry); assert(targets[m.entry],"entry must be an installed file") end
    if m.modules then for mod,target in pairs(m.modules) do assert(type(mod)=="string" and mod:match("^[%a_][%w_.-]*$"),"Invalid module alias"); path(target); assert(targets[target],"Module target not installed") end end
    return m
end
local function read(p)
    local h,e=fs.open(p,"rb"); assert(h,e or ("Cannot read "..p)); local s=h.readAll(); h.close(); return s
end
local function write(p,s)
    fs.makeDir(fs.getDir(p)); local h,e=fs.open(p,"wb"); assert(h,e or ("Cannot write "..p)); h.write(s); h.close()
end
local function clone(x) return data.parse(data.serialize(x)) end
local function encode(s) return (s:gsub("[^%w_.~-]",function(c) return string.format("%%%02X",c:byte()) end)) end
local function download(url,limit,optional)
    assert(http and http.get,"HTTP must be enabled")
    local h,e,failed=http.get({url=url,binary=true,headers={['User-Agent']='CC-LPM/0.1'}})
    if not h then
        local code=failed and failed.getResponseCode(); if failed then failed.close() end
        if optional and code==404 then return nil end
        error("Download failed: "..url..": "..tostring(e),0)
    end
    local chunks,total={},0
    while true do
        local s=h.read(8192); if not s or s=="" then break end
        total=total+#s; if total>limit then h.close(); error("Download too large: "..url,0) end
        chunks[#chunks+1]=s
    end
    h.close(); return table.concat(chunks)
end
local function commit(r)
    if r.ref and #r.ref==40 and r.ref:match("^%x+$") then return r.ref:lower() end
    local url="https://api.github.com/repos/"..r.github.."/commits/"..encode(r.ref or "main")
    local response=textutils.unserializeJSON(download(url,262144))
    assert(type(response)=="table" and type(response.sha)=="string" and #response.sha==40 and response.sha:match("^%x+$"),"GitHub returned invalid commit")
    return response.sha:lower()
end
local function raw(r,ref,p) return "https://raw.githubusercontent.com/"..r.github.."/"..ref.."/"..p end
local function base(r,n) return (r.path and r.path~="" and r.path.."/" or "")..name(n) end
local function project(root)
    local p=data.parse(read(fs.combine(root,"package.lua")))
    assert(p.manifestVersion==1,"Unsupported project schema"); name(p.name); semver.parse(p.version)
    deps(p.dependencies or {}); p.dependencies=p.dependencies or {}
    p.repositories=p.repositories or {default={github="p4ncak3s-R0ck/CC-Tweaked-Stuff",ref="main"}}
    assert(p.repositories.default,"repositories.default required")
    for k,r in pairs(p.repositories) do name(k); repo(r) end
    if p.entry then path(p.entry) end
    return p
end
local function repository(p,n)
    local key=p.packageRepositories and p.packageRepositories[n] or "default"
    return assert(p.repositories[key],"Unknown repository "..tostring(key))
end
local function recover(root)
    local dir=fs.combine(root,".lpm"); local journal=fs.combine(dir,"transaction.lua")
    if not fs.exists(journal) then return end
    local j=data.parse(read(journal)); assert(type(j.hadState)=="boolean" and type(j.hadProject)=="boolean","Invalid recovery journal")
    local current,backup=fs.combine(dir,"current"),fs.combine(dir,"previous")
    local pkg,oldpkg=fs.combine(root,"package.lua"),fs.combine(dir,"previous-package.lua")
    if fs.exists(backup) then if fs.exists(current) then fs.delete(current) end; fs.move(backup,current)
    elseif not j.hadState and fs.exists(current) then fs.delete(current) end
    if fs.exists(oldpkg) then if fs.exists(pkg) then fs.delete(pkg) end; fs.move(oldpkg,pkg)
    elseif not j.hadProject and fs.exists(pkg) then fs.delete(pkg) end
    for dst,original in pairs(j.exports or {}) do
        path(dst); assert(dst~="package.lua" and dst:sub(1,5)~=".lpm/","Invalid recovery export")
        local target=fs.combine(root,dst)
        if original==false then if fs.exists(target) then fs.delete(target) end
        else assert(type(original)=="string","Invalid recovery content"); write(target,original) end
    end
    fs.delete(journal)
end
local function exports(root,lock)
    local out={}
    local function add(dst,n,target)
        path(dst)
        assert(dst~="package.lua" and dst:sub(1,5)~=".lpm/", "Reserved export path")
        local source="/"..fs.combine(root,".lpm/current/packages/"..n.."/"..target)
        local code="-- Managed by lpm. Do not edit.\nlocal fn, err = loadfile("..string.format("%q",source)..", \"t\", _ENV)\nassert(fn, err)\nreturn fn(...)\n"
        assert(not out[dst] or out[dst]==code,"Conflicting package export: "..dst)
        out[dst]=code
    end
    for _,n in ipairs(sorted(lock.packages)) do
        local m=lock.packages[n].manifest
        for _,target in pairs(m.files) do
            if target=="init.lua" then if m.type=="library" then add(n..".lua",n,target) end
            elseif target:sub(-4)==".lua" then add(target,n,target) end
        end
        for mod,target in pairs(m.modules or {}) do add(mod:gsub("%.","/")..".lua",n,target) end
        if m.type=="application" and m.entry then add(n..".lua",n,m.entry) end
    end
    local count=0
    for a in pairs(out) do
        count=count+1; assert(count<=512,"Too many exported modules")
        for b in pairs(out) do assert(a==b or b:sub(1,#a+1)~=a.."/","Export file/directory collision") end
    end
    return out
end
local function activate(root,p,lock,stage)
    local dir=fs.combine(root,".lpm"); local current=fs.combine(dir,"current")
    local backup=fs.combine(dir,"previous"); local oldpkg=fs.combine(dir,"previous-package.lua")
    if fs.exists(backup) then fs.delete(backup) end; if fs.exists(oldpkg) then fs.delete(oldpkg) end
    local exposed=exports(root,lock); local previous={}
    if fs.exists(fs.combine(current,"package.lock")) then previous=data.parse(read(fs.combine(current,"package.lock"))).exports or {} end
    local undo={}
    for dst in pairs(previous) do path(dst); undo[dst]=false end
    for dst in pairs(exposed) do undo[dst]=false end
    for dst in pairs(undo) do
        local target=fs.combine(root,dst)
        if fs.exists(target) then
            assert(not fs.isDir(target),"Directory blocks package module: "..dst)
            local content=read(target)
            assert(previous[dst] and sha256(content)==previous[dst],"Refusing to overwrite existing or edited file: "..dst)
            undo[dst]=content
        end
        local parent=fs.getDir(target)
        while parent~="" do assert(not fs.exists(parent) or fs.isDir(parent),"File blocks module directory: "..parent); parent=fs.getDir(parent) end
    end
    lock.exports={}; for dst,code in pairs(exposed) do lock.exports[dst]=sha256(code) end
    write(fs.combine(stage,"package.lock"),data.serialize(lock))
    write(fs.combine(dir,"next-package.lua"),data.serialize(p))
    local journal=data.serialize({hadState=fs.exists(current),hadProject=fs.exists(fs.combine(root,"package.lua")),exports=undo})
    assert(#journal<=262144,"Recovery journal exceeds metadata limit")
    write(fs.combine(dir,"transaction.tmp"),journal)
    assert(read(fs.combine(dir,"transaction.tmp"))==journal,"Journal write failed")
    fs.move(fs.combine(dir,"transaction.tmp"),fs.combine(dir,"transaction.lua"))
    if fs.exists(current) then fs.move(current,backup) end
    fs.move(fs.combine(root,"package.lua"),oldpkg)
    fs.move(stage,current)
    fs.move(fs.combine(dir,"next-package.lua"),fs.combine(root,"package.lua"))
    for dst in pairs(undo) do
        local target=fs.combine(root,dst)
        if exposed[dst] then write(target,exposed[dst]) elseif fs.exists(target) then fs.delete(target) end
    end
    fs.delete(fs.combine(dir,"transaction.lua")) -- Commit point; backups can now be cleaned.
    if fs.exists(backup) then fs.delete(backup) end; if fs.exists(oldpkg) then fs.delete(oldpkg) end
end
local function validateLock(p,l)
    assert(l.lockVersion==1 and l.projectHash==sha256(data.serialize(p)),"Lockfile does not match package.lua; run lpm update")
    assert(type(l.packages)=="table","Invalid lockfile")
    for n,x in pairs(l.packages) do
        name(n); repo(x.repository); manifest(x.manifest,n)
        assert(x.version==x.manifest.version,"Invalid locked version")
        assert(type(x.commit)=="string" and #x.commit==40 and x.commit:match("^%x+$"),"Invalid locked commit")
        path(x.base); assert(type(x.hashes)=="table","Missing hashes")
        for _,dst in pairs(x.manifest.files) do assert(type(x.hashes[dst])=="string" and #x.hashes[dst]==64 and x.hashes[dst]:match("^%x+$"),"Missing file hash") end
        for dep,r in pairs(x.manifest.dependencies or {}) do assert(l.packages[dep] and semver.satisfies(l.packages[dep].version,r),"Broken locked dependency") end
    end
    for n,r in pairs(p.dependencies) do assert(l.packages[n] and semver.satisfies(l.packages[n].version,r),"Missing locked dependency") end
    return l
end
local function resolve(p)
    local cache,pins={},{}
    local function candidates(n)
        if cache[n] then return cache[n] end
        local r=repository(p,n); local key=data.serialize(r)
        pins[key]=pins[key] or commit(r); local tip=pins[key]; local bp=base(r,n)
        local indexText=download(raw(r,tip,bp.."/index.lua"),262144,true)
        local result={}
        if indexText then
            local idx=data.parse(indexText); assert(idx.indexVersion==1 and type(idx.versions)=="table","Invalid package index")
            local count=0
            for v,entry in pairs(idx.versions) do
                semver.parse(v); assert(type(entry)=="table" and type(entry.ref)=="string" and #entry.ref==40 and entry.ref:match("^%x+$"),"Index versions must pin full commits")
                if entry.path then path(entry.path) end
                count=count+1; assert(count<=128,"Too many package versions")
                result[#result+1]={version=v,commit=entry.ref:lower(),base=entry.path or bp,repository=clone(r)}
            end
            table.sort(result,function(a,b) return semver.compare(a.version,b.version)>0 end)
        else
            local m=manifest(data.parse(download(raw(r,tip,bp.."/manifest.lua"),262144)),n)
            result[1]={version=m.version,commit=tip,base=bp,repository=clone(r),manifest=m}
        end
        cache[n]=result; return result
    end
    local budget=0
    local function solve(chosen,requirements)
        budget=budget+1; assert(budget<=4096,"Dependency resolution exceeded search limit")
        for n,rs in pairs(requirements) do
            if chosen[n] then for _,r in ipairs(rs) do if not semver.satisfies(chosen[n].version,r) then return nil end end end
        end
        local missing
        for _,n in ipairs(sorted(requirements)) do if not chosen[n] then missing=n; break end end
        if not missing then return chosen end
        local count=0; for _ in pairs(requirements) do count=count+1 end; assert(count<=64,"Too many dependencies")
        for _,c in ipairs(candidates(missing)) do
            local fits=true; for _,r in ipairs(requirements[missing]) do if not semver.satisfies(c.version,r) then fits=false end end
            if fits then
                if not c.manifest then c.manifest=manifest(data.parse(download(raw(c.repository,c.commit,c.base.."/manifest.lua"),262144)),missing) end
                assert(c.manifest.version==c.version,"Index version differs from manifest")
                local nextChosen,nextReq=clone(chosen),clone(requirements); nextChosen[missing]=clone(c)
                for dep,r in pairs(c.manifest.dependencies or {}) do nextReq[dep]=nextReq[dep] or {}; table.insert(nextReq[dep],r) end
                local answer=solve(nextChosen,nextReq); if answer then return answer end
            end
        end
    end
    local req={}; for n,r in pairs(p.dependencies) do req[n]={r} end
    return assert(solve({},req),"Incompatible dependency constraints; no valid version set")
end
function M.init(root)
    assert(not fs.exists(fs.combine(root,"package.lua")),"package.lua already exists")
    local n=fs.getName(root):lower():gsub("[^a-z0-9_-]","-"); if not n:match("^[a-z]") then n="project-"..n end
    write(fs.combine(root,"package.lua"),data.serialize({manifestVersion=1,name=n,version="0.1.0",type="application",entry="main.lua",repositories={default={github="p4ncak3s-R0ck/CC-Tweaked-Stuff",ref="main"}},dependencies={}}))
end
function M.install(root,spec,update,remove,offline)
    recover(root); local p=project(root)
    if spec then
        local n,r=spec:match("^([^@]+)@(.+)$"); n=n or spec; name(n)
        if remove then assert(p.dependencies[n],"Not a direct dependency"); p.dependencies[n]=nil
        else r=r or "*"; semver.satisfies("0.0.0",r); p.dependencies[n]=r end
    end
    local dir=fs.combine(root,".lpm"); local current=fs.combine(dir,"current"); local lockPath=fs.combine(current,"package.lock")
    local l
    if not spec and not update and fs.exists(lockPath) then l=validateLock(p,data.parse(read(lockPath)))
    else assert(not offline,"Offline install requires a matching lockfile"); l={lockVersion=1,projectHash=sha256(data.serialize(p)),packages=resolve(p)} end
    local stage=fs.combine(dir,"stage"); if fs.exists(stage) then fs.delete(stage) end; fs.makeDir(stage)
    local total=0
    local ok,err=pcall(function()
        for _,n in ipairs(sorted(l.packages)) do
            local x=l.packages[n]; local previousHashes=x.hashes; x.hashes={}
            for _,src in ipairs(sorted(x.manifest.files)) do
                local dst=x.manifest.files[src]; local bytes
                local existing=fs.combine(current,"packages/"..n.."/"..dst)
                if previousHashes and fs.exists(existing) then
                    local old=read(existing); if sha256(old)==previousHashes[dst] then bytes=old end
                end
                if not bytes then assert(not offline,"Offline file unavailable or corrupt: "..n.."/"..dst); bytes=download(raw(x.repository,x.commit,x.base.."/"..src),MAX_FILE) end
                total=total+#bytes; assert(total<=MAX_TOTAL,"Install exceeds 8 MiB")
                local hash=sha256(bytes); if previousHashes then assert(hash==previousHashes[dst],"SHA-256 mismatch: "..n.."/"..dst) end
                if x.manifest.hashes and x.manifest.hashes[src] then assert(hash==x.manifest.hashes[src],"Manifest hash mismatch") end
                x.hashes[dst]=hash; write(fs.combine(stage,"packages/"..n.."/"..dst),bytes)
            end
        end
        activate(root,p,l,stage)
    end)
    if not ok then recover(root); if fs.exists(stage) then fs.delete(stage) end; error(err,0) end
    return l
end
function M.lock(root)
    recover(root); local p=project(root)
    return validateLock(p,data.parse(read(fs.combine(root,".lpm/current/package.lock")))),p
end
function M.verify(root)
    local l=M.lock(root); local count=0
    for n,x in pairs(l.packages) do for dst,hash in pairs(x.hashes) do
        assert(sha256(read(fs.combine(root,".lpm/current/packages/"..n.."/"..dst)))==hash,"Corrupt file: "..n.."/"..dst); count=count+1
    end end
    for dst,hash in pairs(l.exports or {}) do
        path(dst); assert(sha256(read(fs.combine(root,dst)))==hash,"Edited module loader: "..dst)
    end
    return count
end
function M.setup()
    local startup="startup/lpm-path.lua"
    assert(not fs.exists("startup") or fs.isDir("startup"),"/startup is a file; add /bin to your startup shell path manually")
    local boot='-- Managed package command path\nif shell then shell.setPath("/bin:" .. shell.path()) end\n'
    if fs.exists(startup) then assert(read(startup)==boot,"Existing startup/lpm-path.lua is not managed by lpm") end
    local source=read(shell.getRunningProgram())
    if fs.exists("bin/lpm.lua") then assert(read("bin/lpm.lua"):find("-- LPM ",1,true)==1,"Existing /bin/lpm.lua is not managed by lpm") end
    write("bin/lpm.lua",source); write(startup,boot)
    shell.setPath("/bin:"..shell.path())
end
M.data=data; M.semver=semver; M.sha256=sha256
return M

end
-- Private harness export; ordinary shell usage never takes this path.
if ... == "__lpm_test" then return require("core") end
local M=require("core")
local args={...}
local root=shell.dir()
local help=[=[LPM 0.1.0 - GitHub packages for CC:Tweaked
lpm init                       Create package.lua
lpm install [name[@constraint]] Install/add packages
lpm install --offline          Restore from verified local files
lpm update                     Resolve latest compatible versions
lpm remove name                Remove a direct dependency
lpm list                       Show locked versions and commits
lpm verify                     Verify installed SHA-256 hashes
lpm setup                      Make lpm available from any directory
lpm repo owner/repo [ref] [path] Set default GitHub source
lpm help                       Show help
Constraints: *, 1.2.3, ^1.2.3, ~1.2.3 (stable versions only).
No package scripts or manifests are executed during installation.]=]
local function main()
    local cmd=table.remove(args,1) or "help"
    if cmd=="help" or cmd=="--help" then print(help)
    elseif cmd=="--version" then print(M.version)
    elseif cmd=="init" then assert(#args==0,"Usage: lpm init"); M.init(root); print("Created package.lua")
    elseif cmd=="install" or cmd=="update" or cmd=="remove" then
        assert(#args<=1,"Expected at most one package")
        local offline=args[1]=="--offline"; if offline then args[1]=nil end
        assert(not offline or cmd=="install","--offline is for install")
        assert(cmd~="remove" or args[1],"Usage: lpm remove name")
        assert(cmd~="update" or not args[1],"Usage: lpm update")
        local l=M.install(root,args[1],cmd=="update",cmd=="remove",offline)
        local count=0; for _ in pairs(l.packages) do count=count+1 end
        print("Installed "..count.." packages. Lockfile: .lpm/current/package.lock")
    elseif cmd=="list" then
        local l=M.lock(root); local names={}; for n in pairs(l.packages) do names[#names+1]=n end; table.sort(names)
        for _,n in ipairs(names) do local x=l.packages[n]; print(n.." "..x.version.." "..x.commit:sub(1,12)) end
    elseif cmd=="verify" then print("Verified "..M.verify(root).." files")
    elseif cmd=="setup" then assert(#args==0,"Usage: lpm setup"); M.setup(); print("lpm is available from any directory")
    elseif cmd=="repo" then
        assert(#args>=1 and #args<=3,"Usage: lpm repo owner/repo [ref] [path]")
        assert(args[1]:match("^[%w_.-]+/[%w_.-]+$"),"Invalid owner/repo")
        local pth=fs.combine(root,"package.lua"); local h=assert(fs.open(pth,"r")); local p=M.data.parse(h.readAll()); h.close()
        p.repositories=p.repositories or {}; p.repositories.default={github=args[1],ref=args[2] or "main",path=args[3]}
        h=assert(fs.open(pth,"w")); h.write(M.data.serialize(p)); h.close(); print("Repository configured; run lpm update")
    else error("Unknown command: "..cmd..". Run lpm help",0) end
end
local ok,err=pcall(main)
if not ok then printError("lpm: "..tostring(err)); error("LPM command failed",0) end
