"""Bundle dependency-free lpm.lua for CC:Tweaked."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
parts = ['-- LPM 0.1.0. Generated by tools/build.py.\nlocal loaders, loaded = {}, {}\nlocal hostRequire = require\nlocal function require(n)\n if loaded[n] ~= nil then return loaded[n] end\n if not loaders[n] then return hostRequire(n) end\n local v=loaders[n](); if v==nil then v=true end; loaded[n]=v; return v\nend\n']
for name in ['data', 'semver', 'sha256', 'core']:
    parts.append('loaders[' + repr(name) + '] = function()\n' + (root / 'src' / (name + '.lua')).read_text() + '\nend\n')
parts.append('-- Private harness export; ordinary shell usage never takes this path.\nif ... == "__lpm_test" then return require("core") end\n')
parts.append((root / 'src/cli.lua').read_text())
(root / 'lpm.lua').write_text(''.join(parts))
print('Built', root / 'lpm.lua')
